services:
  api:
    build: 
      context: ./ResumeApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  processor:
    build: 
      context: ./service-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"